In [1]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv('cardio_dataset.csv')

In [3]:
print(df)

      SEX  AGEIR   TC  HDL  SMOKE_  BPMED  DIAB_01  RISK
0       2     48  236   66       0      2        0   1.1
1       1     48  260   51       0      2        1   7.0
2       1     44  187   49       1      2        0   7.0
3       2     42  216   57       1      2        0   0.4
4       2     56  156   42       0      2        0   2.2
...   ...    ...  ...  ...     ...    ...      ...   ...
6639    2     65  307   42       1      1        1  36.6
6640    2     42  169   56       0      1        0   0.8
6641    1     65  212   35       1      1        0  30.6
6642    1     66  184   39       0      1        0  23.8
6643    2     45  203   51       0      2        0   1.0

[6644 rows x 8 columns]


In [5]:
dataset = df.values
print(dataset)

[[  2.   48.  236.  ...   2.    0.    1.1]
 [  1.   48.  260.  ...   2.    1.    7. ]
 [  1.   44.  187.  ...   2.    0.    7. ]
 ...
 [  1.   65.  212.  ...   1.    0.   30.6]
 [  1.   66.  184.  ...   1.    0.   23.8]
 [  2.   45.  203.  ...   2.    0.    1. ]]


In [6]:
data = dataset[:,0:7]
target = dataset[:,7]

In [7]:
print(data)

[[  2.  48. 236. ...   0.   2.   0.]
 [  1.  48. 260. ...   0.   2.   1.]
 [  1.  44. 187. ...   1.   2.   0.]
 ...
 [  1.  65. 212. ...   1.   1.   0.]
 [  1.  66. 184. ...   0.   1.   0.]
 [  2.  45. 203. ...   0.   2.   0.]]


In [8]:
print(target)

[ 1.1  7.   7.  ... 30.6 23.8  1. ]
